language: python

python:
  - "2.7"
  - "pypy"

install:
  - sudo apt-get update -qq
  - sudo apt-get install protobuf-compiler
  - pip install -r requirements.txt --use-mirrors

script: nosetests

notifications:
  email: false
